[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.17"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
regex = "1.10.2"
